/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#define INBUF_SIZE 4096
#define AUDIO_INBUF_SIZE 20480
#define AUDIO_REFILL_THRESH 4096
#define LOGE(format, ...)  __android_log_print(ANDROID_LOG_ERROR, "(>_<)", format, ##__VA_ARGS__)
#define LOGI(format, ...)  __android_log_print(ANDROID_LOG_INFO,  "(^_^)", format, ##__VA_ARGS__)
#include "libavcodec/avcodec.h"
#include "libavformat/avformat.h"
/* Header for class com_borqs_audio_Ffmpeg */

#ifndef _Included_com_borqs_audio_Ffmpeg
#define _Included_com_borqs_audio_Ffmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_borqs_audio_Ffmpeg
 * Method:    avcodec_find_decoder
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_borqs_audio_Ffmpeg_avcodecFindDecoder
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_borqs_audio_Ffmpeg
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_borqs_audio_Ffmpeg_create
  (JNIEnv *, jobject);

/*
 * Class:     com_borqs_audio_Ffmpeg
 * Method:    setFilePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_borqs_audio_Ffmpeg_setFilePath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_borqs_audio_Ffmpeg
 * Method:    getFrameByte
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_borqs_audio_Ffmpeg_getFrameByte
  (JNIEnv *, jobject);

/*
 * Class:     com_borqs_audio_Ffmpeg
 * Method:    start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_borqs_audio_Ffmpeg_start
  (JNIEnv *, jobject);

/*
 * Class:     com_borqs_audio_Ffmpeg
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_borqs_audio_Ffmpeg_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_borqs_audio_Ffmpeg
 * Method:    pause
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_borqs_audio_Ffmpeg_pause
  (JNIEnv *, jobject);

/*
 * Class:     com_borqs_audio_Ffmpeg
 * Method:    resume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_borqs_audio_Ffmpeg_resume
  (JNIEnv *, jobject);

/*
 * Class:     com_borqs_audio_Ffmpeg
 * Method:    seekPosition
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_borqs_audio_Ffmpeg_seekPosition
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_borqs_audio_Ffmpeg_audioDecode
    (JNIEnv *env, jobject obj, jstring input_jstr, jstring output_jstr);

void custom_log(void *ptr, int level, const char* fmt, va_list vl);

#ifdef __cplusplus
}
#endif
#endif
